Practice 5
Myroslava-Movchan/OOP_Online_Store_Management pull request #5
Opened 2024-10-24 15:04 UTC by Myroslava-Movchan

practice 5 tasks

2024-10-25 11:38 UTC, BraveheartMousy requested changes
Almost all good except HttpClient, which I would ask to rewrite it to receive a grade. Just let me know if you need any help, I am ready to help

2024-10-25 11:38 UTC, BraveheartMousy commented on Online Store Management/Services/CustomerService.cs
>              if (_disposed)
Since you removed IDisposable pattern, you can remove all the rest of its implementation, we do not need it anymore. 
Like private bool _disposed = false; and if (_disposed)

2024-10-25 11:38 UTC, BraveheartMousy commented on Online Store Management/Interfaces/ICustomer.cs
> +        void Dispose();
No need to keep this method, if class implements IDisposable interface it already contains method Dispose();, no need to define it is a custom way in your ICustomer interface

2024-10-25 11:38 UTC, BraveheartMousy commented on Online Store Management/Models/Product.cs
> +    public struct ProductStruct
Each new class and struct is recommended to have in a separate file. It is a code-style recommendation, no tech issue or error.

2024-10-25 11:38 UTC, BraveheartMousy commented on Online Store Management/Models/Customer.cs
> +        public  void Recommendation()
Pay attention to double spaces and unnecessary repeatable empty lines between methods

2024-10-25 11:38 UTC, BraveheartMousy commented on Online Store Management/Infrastructure/CatalogueClient.cs
> +            var imageUrls = ExtractImageUrlsFromHtml(htmlContent);
I am now sure it will correctly indicate ImageUrls. It's always empty for me when I run the program.

2024-10-25 11:38 UTC, BraveheartMousy commented on Online Store Management/Infrastructure/CatalogueClient.cs
> +        private const string SocksCategoryUrl = "https://maikbook.com/?product_cat=socks";
I suggest rewriting this HttpClient a little bit. 
Instead of socks store where you are trying to use scraping technique, it is better to call API that explicitly returns iteams, not HTML that you need to pars with regex, and latter when they change HTML layout your program stop work and will require changes. 

I suggest using Fake Store API and specifically URL: https://fakestoreapi.com/products
It returns model with ready image Urls which you can parse easier
![image](https://github.com/user-attachments/assets/85021ae4-bab8-4f7d-becc-52f14f7c8f44)

2024-10-25 11:38 UTC, BraveheartMousy commented on Online Store Management/Models/Customer.cs
>      public class RegularCustomer : Customer
It is better to place each new class to separate file

2024-10-25 11:58 UTC, BraveheartMousy commented on Online Store Management/Infrastructure/CatalogueClient.cs
> +        private const string SocksCategoryUrl = "https://maikbook.com/?product_cat=socks";
You can have class 
```
public class ExternalProduct {
  public int Id { get; set; }
  public string Tittle { get; set; }
  public decimal Price { get; set; }
  public string Description { get; set; }
  public string Category { get; set; }
  public string Image { get; set; }
  public ProductRating Rating { get; set; }
}
```

```
public class ProductRating  {
  public int Count { get; set; }
  public decimal Rate { get; set; }
}
```

`await response.Content.ReadFromJsonAsync<ExternalProduct>(cancellationToken);`

or 
```
var jsonData = await response.Content.ReadAsStringAsync(cancellationToken);
ExternalProduct product = JsonSerializer.Deserialize<ExternalProduct>(jsonData);
```

2024-10-27 14:47 UTC, Myroslava-Movchan commented on Online Store Management/Infrastructure/CatalogueClient.cs
> +        private const string SocksCategoryUrl = "https://maikbook.com/?product_cat=socks";
changed it, please check

2024-10-27 18:26 UTC, liudmyla-zinchenko approved these changes
Great! Thank you

2024-10-28 08:06 UTC, merged