Practice 6
Myroslava-Movchan/OOP_Online_Store_Management pull request #6
Opened 2024-10-31 17:39 UTC by Myroslava-Movchan

I added LINQ in services where it is possible to choose something with some condition from the list full of same-type things. All the methods in services and controllers were changed to async according to the task. Generic class was implemented according to the example.

2024-11-01 11:27 UTC, BraveheartMousy requested changes
Cannot check whether program works correctly, because method async Task AddAsync(Customer entity, CancellationToken cancellationToken) in Repository is never called. 

Please implement in the Controller calls that corresponds HTTP GET, POST, PUT, DELETE, they all should interact with Repository methods, so as a user I am able to add, update, delete and get entity

2024-11-01 11:27 UTC, BraveheartMousy commented on Online Store Management/Controllers/CustomerController.cs
>          {
I see this endpoint still responses with 204 which corresponds to No Content Http status code. 
This is because you use Customer model which is abstract class, if you will change it to any usual class it will works a little bit different and you will able to have cod like this 
```
 if (result == null || result.Id == 0)
 {
     return new Customer() { };
 }
```

To better manage it you can change code to what is shown at the screen
![image](https://github.com/user-attachments/assets/680249a6-02fa-4d9b-9013-5b840ad0b261)


This comments just FYI not to direct fix, the way you have implemented is not wrong

2024-11-05 19:30 UTC, Myroslava-Movchan commented on Online Store Management/Controllers/CustomerController.cs
>          {
added reqired changes and fixed GetAsync, please check whether I did what you asked me to do.

2024-11-06 14:22 UTC, liudmyla-zinchenko commented on Online Store Management/Controllers/CustomerController.cs
> +        /*[HttpGet("regular")]
One method left commented

2024-11-06 14:23 UTC, BraveheartMousy approved these changes
Good

2024-11-06 18:10 UTC, merged